version: '3'

services:
  api:
    build: .
    image : voting-api
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      PORT: "8080"
    depends_on:
      - redisserver   

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

